### PR TITLE
SpecificationRepository as trait

### PR DESCRIPTION
**Pull request by alle**
I second @juliangut as in #17 to make the SpecificationRepository as a trait, in order to be used in other repositories.

### CODE REVIEW

**Comment by juliangut** [comment]
An `SpecificationAware` interface would be nice

**Comment by rikbruil** [comment]
Thanks for the PR, I agree an interface and trait would be useful.

I will merge this and tag it a little bit later.

**Comment by rikbruil** [comment]
FYI: I renamed SpecificationAware to SpecificationAwareInterface in #20 

I did this for consistency in naming, otherwise haven't touched the code.

**Comment by alle** [comment]
@rikbruil OK, I got that.

**Comment by juliangut** [comment]
Nice! :+1:

**Pull request merged**
